# Generated by Django 4.1.7 on 2023-03-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_two_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
